UX-948/change-sku-to-Standard_A4_v2-for-Azure
platform9/pf9-ui-plugin pull request #1067
Opened 2021-05-21 04:56 UTC by hgupta2363

<img width="882" alt="Screenshot 2021-05-21 at 10 03 02 AM" src="https://user-images.githubusercontent.com/48471809/119084155-e80ec780-ba1e-11eb-909e-49cd6f4f198e.png">

2021-05-24 21:30 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/custom.tsx
> +  { label: 'Md - 1 Master + 3 Workers (Standard_A4_v2)', value: 'medium' },
all you are doing here is just changing a string for presentation purposes. This doesn't change the template. further down the file there is a function called `handleTemplateChoice` that is what actually sets the SKU, update those strings to be the correct value please. Also, since its always the same lets remove `(Standard_A4_v2)` from the option text and instead put the SKU type in the label of the dropdown itself

2021-05-24 21:31 UTC, jruddell requested changes
all you are doing here is just changing a string for presentation purposes. This doesn't change the template. further down the file there is a function called `handleTemplateChoice` that is what actually sets the SKU, update those strings to be the correct value please. Also, since its always the same lets remove `(Standard_A4_v2)` from the option text and instead put the SKU type in the label of the dropdown itself

2021-05-25 19:34 UTC, jruddell requested changes
One missing piece of the feedback i left is that we use this template name as the label of the dropdown component. `Standard_A4_v2` needs to be added to `form-components/cluster-templates.tsx` under the `label` prop. This way the developers know what template is being used still

2021-05-27 05:42 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/cluster-templates.tsx
> +  <PicklistField id="template" label="Standard_A4_v2" options={options} onChange={onChange} />
Think about this, if you are trying to use the UI and all you see is the title of a dropdown with this text. What does that mean? Obviously we should keep the `Cluster Template` title and rather like I was saying in my prior comments add `(Standard_A4_v2)` to the end so they know what template they are dealing with.

2021-05-27 06:06 UTC, hgupta2363 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/cluster-templates.tsx
> +  <PicklistField id="template" label="Standard_A4_v2" options={options} onChange={onChange} />
oh yeah, this gave me a lesson. Read the requirements carefully

2021-05-27 08:52 UTC, jruddell approved these changes

2021-06-02 04:24 UTC, merged