UX-968, UX-989, UX-990/Add GKE cloud provider and cluster import features
platform9/pf9-ui-plugin pull request #1080
Opened 2021-06-09 22:51 UTC by kevinylee1991

<img width="1556" alt="Screen Shot 2021-06-09 at 3 46 21 PM" src="https://user-images.githubusercontent.com/6668478/121439321-94ffa480-c93a-11eb-8b2d-e37d99bfa883.png">
<img width="1555" alt="Screen Shot 2021-06-09 at 3 46 45 PM" src="https://user-images.githubusercontent.com/6668478/121439329-9761fe80-c93a-11eb-8fbf-adb1b83df55a.png">
<img width="1557" alt="Screen Shot 2021-06-09 at 3 51 24 PM" src="https://user-images.githubusercontent.com/6668478/121439331-97fa9500-c93a-11eb-99e2-51706c96b0d4.png">

2021-06-11 05:13 UTC, pallabpain commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +  [CloudProviders.GKE]: testsForGoogle,
Can we rename this to `CloudProvider.GCP` instead?

2021-06-14 17:54 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +  [CloudProviders.GKE]: testsForGoogle,
under cloud providers yes we should call this GCP or even just `Google`.

2021-06-14 17:56 UTC, jruddell commented on src/app/plugins/kubernetes/components/common/CloudProviderCard.tsx
> +  [CloudProviders.Google]: `${rootPath}/cloudgoogle-default${iconSize}.png`,
dont we have different icons for google vs gke?

2021-06-14 18:00 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/GoogleCloudProviderVerification.tsx
> +  console.log(regions, 'regions')
console.log

2021-06-14 18:00 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
> +  console.log(initialValues, 'initialValues')
console.log

2021-06-14 18:12 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/selectors.ts
> +  gke: 'Google',
why is gke a cloud provider type? isn't it a cluster type?

2021-06-14 18:28 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/import/actions.ts
> +  console.log(data, 'cluster data')
console.log

2021-06-14 18:33 UTC, jruddell requested changes
lets fix the enums, GKE isn't a cloud provider its a type of cluster that is imported from google. few other comments / some minor cleanup

2021-06-14 21:32 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/common/CloudProviderCard.tsx
> +  [CloudProviders.Google]: `${rootPath}/cloudgoogle-default${iconSize}.png`,
nope, just the one

2021-06-14 22:11 UTC, jruddell approved these changes

2021-06-14 22:12 UTC, merged