UX-924/cluster-upgrade design created
platform9/pf9-ui-plugin pull request #1081
Opened 2021-06-10 18:58 UTC by rajshekhar23

2021-06-14 16:11 UTC, jruddell commented on package.json
> +    "yarn": "^1.22.10"
why is yarn added as a dependency?

2021-06-14 16:12 UTC, jruddell commented on src/app/core/components/validatedForm/radio-fields.tsx
> -import { FormControl, FormControlLabel, FormHelperText, Radio, WithStyles } from '@material-ui/core'
probably best to just remove the changes to this file since we didnt go forward with this work

2021-06-14 16:13 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +function intersection(a, b) {
we have a library called Ramda that we use for things like this. I believe they have an `intersection` method you can use

2021-06-14 16:13 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +  console.log('clusterNodes', clusterNodes)
console.log

2021-06-14 16:13 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +  console.log(leftChecked, rightChecked)
console.log

2021-06-14 16:15 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +      <Grid item>
we dont use grid much at all. Lets try to avoid the unnecessary elements

2021-06-14 16:15 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +            variant="outlined"
remove commented out code

2021-06-14 17:10 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  console.log('cluster', cluster)
console.log

2021-06-14 17:12 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                          {/* <FormFieldCard title="Upgrade Strategy">
remove commented out code

2021-06-14 17:13 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/cluster-node-upgrade-strategy.tsx
> +      value={wizardContext['sequentialStrategy']}
use `.` notation for accessing properties instead of `['`

2021-06-14 17:14 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/percentage-cluster-upgrade.tsx
> +      step="1"
we should have a min and max range for this input. 1 -> 100

2021-06-14 17:16 UTC, jruddell commented on src/stories/config.js
> -import StoryRouter from 'storybook-react-router'
2 things. you shouldn't be pushing the config.js file, make sure this is removed. This is also inside stories which is the wrong location

2021-06-14 17:19 UTC, jruddell requested changes
couple changes in code style and some cleanup, make sure you always review the change log before making the pull request. Also I didn't see anything about you sending this data in the API request for the backend to use. Just because the element has been added to the page and its data is tracked in the wizardContext, you still need to pass the data through in the API call. look at how we generate the payload for creating a cluster (cluster/actions.js has the create function, it calls helper methods to build the payload inside cluster/helpers.ts)

2021-06-15 05:47 UTC, rajshekhar23 commented on package.json
> +    "yarn": "^1.22.10"
@jruddell  may be i tried multiple ways to make yarn working. globally installed yarn was not working so i tried to install that only current repository.

I will remove it quickly

2021-06-30 19:46 UTC, jruddell commented on src/api-client/Qbert.ts
> +    if (body) {
why do you need to do this?

2021-06-30 19:51 UTC, rajshekhar23 commented on src/api-client/Qbert.ts
> +    if (body) {
@jruddell to differentiate three scenarios based on body value.
if something is there in body ( batchUpgradeNodes or batchUpgradePercent) then will go inside body params.
else body wont get added into end point.

2021-06-30 20:14 UTC, rajshekhar23 commented on src/api-client/Qbert.ts
> +    if (body) {
@jruddell Updated.

2021-06-30 21:26 UTC, xantorres requested changes

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = partition(
please use `useMemo` here, it looks like an expensive operation

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = partition(
`useMemo`

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    [upgradeType],
This dependency is not used anywhere in the callback function, so you can remove it

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    [upgradeClusterNodes],
You can remove this dependency here.

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                      {({ setFieldValue, values }) => (
Why are we even using `ValidatedForm` here if we are not setting the form values or doing any validation? You are essentially bypassing the `ValidatedForm` and just using the `Wizard` values

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +  Bugsnag.leaveBreadcrumb('Attempting to upgrade cluster on percentage', {
Not a fan of moving the tracking stuff to the helpers file

2021-06-30 21:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/monitoring/AlarmOverviewClusters.tsx
> +          <div className={classes.clustersList} key={cluster?.uuid}>
If a `cluster` is nil something has had to go very wrong before we got here

2021-06-30 21:26 UTC, xantorres commented on yarn.lock
> +"@babel/compat-data@^7.13.11", "@babel/compat-data@^7.14.4":
Why has this file been updated?

2021-07-01 06:22 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    marginBottom: '10px !important',
@xantorres  !important needed to add margin-bottom because SearchBar component is having !important for margin 0px with !important.

2021-07-01 06:33 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +  const renderList = (items, listName) => (
@xantorres used useCallback and wrapped complete function inside useCallback.

2021-07-01 06:37 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +  const handleLeftSearchChange = (search) => setSearchLeft(search)
@xantorres it is outside render body itself.

2021-07-01 07:37 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    setLeft(
@xantorres I tried but its not working. not getting how to use useMemo here at useEffect.

2021-07-01 07:38 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +function uniqueList(list) {
@xantorres updated with ramda function uniqBy

2021-07-01 07:39 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    [upgradeClusterNodes],
@xantorres  removed.

2021-07-01 08:07 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +  Bugsnag.leaveBreadcrumb('Attempting to upgrade cluster on percentage', {
@xantorres removed and added back to clusters/actions.js file.

2021-07-01 08:12 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/monitoring/AlarmOverviewClusters.tsx
> +          <div className={classes.clustersList} key={cluster?.uuid}>
@xantorres I changed this file because i was getting some typescript error. I undo only the changes which i updated.

2021-07-01 08:16 UTC, rajshekhar23 commented on yarn.lock
> +"@babel/compat-data@^7.13.11", "@babel/compat-data@^7.14.4":
@xantorres i installed all the packages again. May be that time it got updated. I removed changes from this file.

2021-07-01 08:57 UTC, xantorres commented on src/app/core/elements/transfer-list.tsx
> +  const handleLeftSearchChange = (search) => setSearchLeft(search)
This whole `TransferList` is a render function, please declare as much stuff outside of this function as possible.

2021-07-01 16:35 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +    <>
@xantorres Removed from all files wherever added.

2021-07-01 16:39 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    [upgradeType],
@xantorres removed.

2021-07-01 17:53 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = partition(
@xantorres Updated with useMemo.

2021-07-01 17:53 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = partition(
@xantorres Updated with useMemo

2021-07-06 18:49 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +    marginBottom: '10px !important',
Dont put a margin on the search box as it is. Use the parent component to define the layout. if you need help with this ill do it with you on a call

2021-07-06 18:56 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +    setRight(uniqBy(prop('uuid') as any, right.concat(leftChecked)))
you shouldnt need to cast to any type here, lets hop on a call and go over the typing issues you have an ill help resolve

2021-07-06 19:02 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +      ? right.filter((value) => value.name.toLowerCase().includes(searchRight.toLowerCase()))
`value?.name?.toLowerCase()?.includes` if name isn't a string this will throw an exception.

2021-07-07 07:32 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    marginBottom: '10px !important',
@jruddell applied as mentioned using parent component.

2021-07-07 07:51 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +      ? right.filter((value) => value.name.toLowerCase().includes(searchRight.toLowerCase()))
@jruddell added as mentioned

2021-07-07 07:57 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    setRight(uniqBy(prop('uuid') as any, right.concat(leftChecked)))
@jruddell I just removed 'as any' and its working fine.

2021-07-08 19:48 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +    '& .MuiOutlinedInput-adornedEnd': {
what I meant by letting the parent define layout is to use something like grid and to remove the margin. If you can use css grid or flexbox to handle layout / placement (like centering with align-items and justify-content instead of a margin to do that)

2021-07-08 19:49 UTC, jruddell commented on src/api-client/Qbert.ts
> +    const upgradeClusterNodesOptions = {
this doesn't have any purpose as a variable when you can just pass it inline. Since thats the pattern lets stick with that

2021-07-08 20:16 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +function comparer(otherArray) {
We generally default to using arrow syntax especially when they return functions. The name `comparer` is pretty weird it would be better to have a more explicit name about what the function is doing.

2021-07-08 20:19 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +        return other.name === current.name
why compare on name? name isn't a unique field for a node and can change. I would stick with uuid for your equality comparison

2021-07-08 20:20 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +  const [left, setLeft] = React.useState(clusterNodes)
Maybe we should think about the data structure here some. If there are 7k nodes managing these data sets and iterating over them all is going to be a hit to performance. Maybe instead we should use an object, key the elements by uuid?

2021-07-08 20:21 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +export const filterInInitialUpgrade = (targetVersion) => (node) =>
what is the point of these two helper methods? they do exactly the same thing

2021-07-08 20:23 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +    return partition(
there is a bug here, i dont see you actually using the `upgradingTo` property on the cluster when comparing versions. if a user selects a version how is that handled here?

2021-07-08 20:25 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  wizardContext,
why is this dialog accepting the wizard context? its a dialog, not attached or related to the wizard context. You should only pass what the component needs to use instead of giving it the whole wizard context.

2021-07-08 20:28 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
> +      routeTo: (rows) => `/ui/kubernetes/infrastructure/clusters/${rows[0].uuid}/upgrade`,
we have a `routes` file that defines all our routes. please use this instead of hardcoding the string. 

for instance a few lines up from here ~line 293, thats what it is for me you have this. `editUrl: (_, id) => routes.cluster.edit.path({ id }),`. Lets reuse this pattern as it makes changing routes / refactoring much easier

2021-07-08 20:31 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    field,
what is the purpose of putting `field` here on this object? isn't field a boolean?

2021-07-08 20:33 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  cluster.upgradeType = defaultState
why are you mutating a record like this? whats the purpose of it?

2021-07-08 20:34 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  const wizardMetaFormattedNames = {
this is a constant, define it outside of the component

2021-07-08 20:35 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  const wizardMetaCalloutFields = ['name', 'version', 'masterNodes', 'workerNodes', 'networkPlugin']
this is a constant, define it outside of the component. Also since it's directly related to the formatted names variable it would make more sense to change this to `const wizardMetaCalloutFields = Object.keys(wizardMetaFormattedNames)`

2021-07-08 20:37 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +      if (wizardContext.sequentialClusterUpgrade) {
this code is bloated, both if checks for `percentageClusterUpgrade` and `sequentialClusterUpgrade` do the same thing.

2021-07-08 20:37 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  cluster.selectedUpgradeVersion =
why are you mutating a record like this? whats the purpose of it?

2021-07-08 20:38 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    const selectedUpgradeVersion =
im seeing this code repeated multiple times. This also looks like its error prone. Just because a cluster can do a minor upgrade doesn't mean the user has chosen that option.

2021-07-08 20:41 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                  icon={<CloudProviderCard active type={cluster.cloudProviderType} />}
a cluster's cloud provider type doesn't directly map to an icon. bareos clusters are all listed as type `local` except the icons want to know if a `local` provider is a VM or PM (virtual vs physical). You need to determine if this is one of those two types when the cloud provider is of type `local`

2021-07-08 20:44 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
> +      const updatedCluster = createBatchUpgradeClusterPayload(formData)
this is going to throw an exception when it goes through all the way, have you tested this? `createBatchUpgradeClusterPayload` is an async function that does an API call, if you dont await for it then you are going to store the pending promise as the cluster record

2021-07-08 20:47 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = useMemo(() => {
this is another duplicated piece of code that also isn't taking into account and or even using the `upgradingTo` value to compare versions. Have you tested this?

2021-07-08 20:52 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +export default function TransferList({ clusterNodes, setWizardContext }) {
why does transferList take `setWizardContext` and `clusterNodes` as props? This is a generic component, it should just take a list of items and an updater that are generic in name as its a common reusable element

2021-07-08 20:54 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/percentage-cluster-upgrade.tsx
> +  }: { wizardContext: any; setWizardContext: any } = useContext(WizardContext) as any
why do you need to pull in wizardcontext here? the values should have everything on it you'd need

2021-07-08 20:54 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  }: { wizardContext: any; setWizardContext: any } = useContext(WizardContext) as any
why do you need to pull in wizardcontext here? the values should have everything on it you'd need

2021-07-08 20:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/sequential-cluster-upgrade.tsx
> +export const SequentialClusterUpgradeAddonField = () => {
dont define this component if it doesn't do anything. in the addon manager, you can specify null instead of a component that renders null

2021-07-08 20:57 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +export const createBatchUpgradeClusterPayload = async (data) => {
the name of this is misleading. If it is generating the payload then thats what it should do. if its going to request from the API then it should be named in a way that you can understand thats what its doing. when i first read the name of this function (when you were using it) i thought it only generated a payload to send to the API

2021-07-08 20:58 UTC, jruddell requested changes
Do another pass over the code, fix up the issues and please make sure you test this.

2021-07-12 10:23 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +export const filterInInitialUpgrade = (targetVersion) => (node) =>
@jruddell updated.

2021-07-12 10:29 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +    return partition(
@jruddell Updated.

2021-07-12 10:40 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  wizardContext,
@jruddell I am setting  wizardContext as "batchUpgradeNodes" ( selected nodes to upgrade) in transfer-list and It will show same batchUpgradeNodes list from wizardContext on ClusterBatchUpgradeDialog.

2021-07-12 11:34 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
> +      routeTo: (rows) => `/ui/kubernetes/infrastructure/clusters/${rows[0].uuid}/upgrade`,
@jruddell Updated same as mentioned.

2021-07-12 12:12 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    field,
@jruddell Earlier I thought set the field name to wizardContext to compare later. forgot to remove the field key from **handleSetUpgradeStrategy** function.

2021-07-12 12:14 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    '& .MuiOutlinedInput-adornedEnd': {
@jruddell Updated using display: grid

2021-07-12 12:16 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  cluster.upgradeType = defaultState
@jruddell In ClusterBatchUpgradeDialog filtering upgraded and non-upgraded nodes we need to pass upgradingTo value for the comparison which we get it from cluster object.

2021-07-12 12:19 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  const wizardMetaFormattedNames = {
@jruddell Updated added outside of the component

2021-07-12 12:20 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  const wizardMetaCalloutFields = ['name', 'version', 'masterNodes', 'workerNodes', 'networkPlugin']
@jruddell Right. Updated same

2021-07-12 12:22 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +      if (wizardContext.sequentialClusterUpgrade) {
@jruddell Right. Updated as **if (wizardContext.percentageClusterUpgrade || wizardContext.sequentialClusterUpgrade) {**

2021-07-12 12:47 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  cluster.selectedUpgradeVersion =
@jruddell Removed.

2021-07-12 13:10 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    const selectedUpgradeVersion =
@jruddell Updated handleChange function and thats why i was added a line 
**cluster.upgradeType = defaultState**
 defaultSelection of upgradeType if only one option available to upgrade on the form.

2021-07-12 14:52 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
> +      const updatedCluster = createBatchUpgradeClusterPayload(formData)
@jruddell Right. Added await while calling createBatchUpgradeClusterPayload function.

2021-07-12 14:54 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const [upgradedNodes, toBeUpgradedNodes] = useMemo(() => {
@jruddell. Updated and tested

2021-07-12 15:08 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +export default function TransferList({ clusterNodes, setWizardContext }) {
Right @jruddell removed setWizardContext and added callback to send selected nodes values back to component.

2021-07-12 15:40 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/sequential-cluster-upgrade.tsx
> +export const SequentialClusterUpgradeAddonField = () => {
@jruddell Removed and added null.

2021-07-12 15:44 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +export const createBatchUpgradeClusterPayload = async (data) => {
@jruddell Updated function name as **upgradeNodesCluster**

2021-07-12 15:57 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  }: { wizardContext: any; setWizardContext: any } = useContext(WizardContext) as any
@jruddell values does not have **batchUpgradePercent** and **batchUpgradeNodes**. These values are set by **setWizardContext** callback and are getting stored in wizardContext only not in **values** prop.

Not sure why values is not getting updated once i set value using setWizardContext function.

2021-07-12 17:18 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/percentage-cluster-upgrade.tsx
> +  }: { wizardContext: any; setWizardContext: any } = useContext(WizardContext) as any
@jruddell batchUpgradePercent is set using setWizardContext which is getting added into values prop of the component.

2021-07-12 17:31 UTC, rajshekhar23 commented on src/api-client/Qbert.ts
> +    const upgradeClusterNodesOptions = {
@jruddell Updated.

2021-07-12 19:54 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +function comparer(otherArray) {
@jruddell  Updated and changed function name.

2021-07-12 19:54 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +        return other.name === current.name
@jruddell  Updated

2021-07-13 06:16 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                  icon={<CloudProviderCard active type={cluster.cloudProviderType} />}
@jruddell Resolved and able to see VM/PM icon.

2021-07-13 17:16 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +    <ListItem
try to use regular html elements here as material ui elements have a lot of additional stying like ripples that cause performance issues

2021-07-26 18:04 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +  LEFT = 'left',
the naming convention we use for enums is 
```
enum ItemTypes {
  Left = 'left',
  Right = 'right'
}
```

2021-07-26 18:10 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +    item.forEach((item) => {
dont reuse the same variable name. its a param to the parent function.

2021-07-26 18:13 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(cluster)
what about the node version a user is selecting?

2021-07-26 18:15 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    item = Array.isArray(item) ? item : [...[], item]
@jruddell  [...[], newItem]

trying to convert single newItem into array if the type if newItem is not Array.

2021-07-26 18:16 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +    item.forEach((item) => {
@jruddell Updated

2021-07-26 18:18 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(cluster)
@jruddell its working by the same logic getting version based on two values as cluster.minorUpgradeRoleVersion and cluster.patchUpgradeRoleVersion

2021-07-26 18:32 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                        clusterType.includes('virtual')
this logic should be in a helper function

2021-07-26 18:35 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                            <RadioGroup
if im not mistaken you can supply an ID to the RadioGroup component and use it like the other elements on the wizard. I'm not sure why you are managing this field separately.

2021-07-26 18:37 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +  const [showModal, setModal] = useState(false)
@jruddell Updated variable for Modal enabling as '**isClusterBatchUpgradeDialogEnabled**'

2021-07-26 18:39 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(values)
all of this version comparison stuff is going to be error prone. Why not just set the current version to be used in the wizard? that current version can be `cluster.upgradingTo`, the version the user selects... etc. And then these components are just consuming the `currentUpgradeVersion` (or whatever you'd like to call it)

2021-07-26 18:42 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(cluster)
until a user chooses a different option?

2021-07-27 12:59 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterBatchUpgradeDialog.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(cluster)
@jruddell Updated.

2021-07-27 13:08 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                        clusterType.includes('virtual')
@jruddell Added in helper file function called **fetchIconByClusterType**

2021-07-27 13:09 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                            <RadioGroup
@jruddell Updated as discussed using radio-fields.tsx file.

2021-07-27 18:44 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/advanced-batch-upgrade.tsx
> +  const nodeVersionToCompare = getNodeVersionToCompare(values)
@jruddell  Updated

2021-07-28 21:42 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +      Object.keys(newChecked[itemType]).forEach((key) => delete newChecked[itemType][key])
what is the purpose of this?

2021-07-28 21:43 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    cluster.upgradeType = { type: defaultState, version: cluster?.upgradingTo }
why are you mutating the cluster object again? I've gone over this already, don't mutate objects like this.

2021-07-28 21:54 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                              value={wizardContext?.upgradeType}
the upgrade type you are defining on the cluster is not what this component expects. it should be the string version. using an object as the value can be problematic because you then are relying on a referrential check of an object. if its cloned but still the same "value" they will not appear checked. you should instead flatten out the options here to be both stored on the wizard.  `onChange({ upgradeVersion: value, upgradeType: UpgradeTypes.Patch})`

2021-07-28 21:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +  return clusterType?.includes('virtual')
the point of moving this to a function was to clean up the ternary hell you have currently. Please change this to use  if statement checks for virtual and physical

2021-07-29 14:43 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +      Object.keys(newChecked[itemType]).forEach((key) => delete newChecked[itemType][key])
@jruddell onSelectAll checkbox event if return value is empty, then all the checked keys of [left|right] side need to be deleted.

2021-07-29 14:47 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
> +  return clusterType?.includes('virtual')
@jruddell  updated

2021-07-29 22:50 UTC, jruddell commented on src/app/core/elements/transfer-list.tsx
> +      Object.keys(newChecked[itemType]).forEach((key) => delete newChecked[itemType][key])
so then just make it an empty object? `newChecked[itemType] = {}`

2021-07-30 06:41 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +                              value={wizardContext?.upgradeType}
@jruddell to flatten the object, RadioFields component is not returning object on handleChange. it is just value.

2021-07-30 06:41 UTC, rajshekhar23 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/UpgradeClusterPage.tsx
> +    cluster.upgradeType = { type: defaultState, version: cluster?.upgradingTo }
@jruddell Updated

2021-07-30 06:41 UTC, rajshekhar23 commented on src/app/core/elements/transfer-list.tsx
> +      Object.keys(newChecked[itemType]).forEach((key) => delete newChecked[itemType][key])
@jruddell Updated

2021-08-04 17:43 UTC, xantorres commented on src/app/core/components/validatedForm/ValidatedForm.js
> +              <AddonDetailCards
This looks like a bad design to me, why is ValidatedForm even aware of ClusterAddonManager, and why does it have to explicitly pass anything to it? 
I think it should be the other way around, ClusterAddonManager rendering a ValidatedForm, and using a `withFormContext` HoC or a `useContext` hook to avoid polluting this already complicated component with external knowledge or responsibilities.

2021-08-04 17:45 UTC, xantorres commented on src/app/core/elements/transfer-list.tsx
> +      left: { ...left },
why not just `const itemsBySide = { right, left }`?

2021-08-04 19:38 UTC, jruddell commented on src/app/core/components/validatedForm/ValidatedForm.js
> +              <AddonDetailCards
hmm, the addon manager was meant to be a more simple form component mapping to rendering a detail card with more form fields. this is required to be inside the validated form as its rendering form elements. When we discussed this last I think the conclusion was it made the most sense to have this be attached via validated form.

2021-08-04 19:44 UTC, jruddell approved these changes

2021-08-04 19:47 UTC, merged