UX-997/Add Profile Engine to AddOnManager
platform9/pf9-ui-plugin pull request #1096
Opened 2021-06-24 22:52 UTC by knnguy

### **Description:**

- Added Profile Engine as an option to the cluster add-ons section 

- It's available in these cluster creation forms:
   - AWS custom
   - Azure custom
   - BareOs Physical single and multi-master
   - BareOs Virtual single and multi-master

- The Profile Engine checkbox will only show up if the user selects a Kubernetes version that is >= 1.20

![Screen Shot 2021-06-24 at 3 42 41 PM](https://user-images.githubusercontent.com/23369276/123341735-56a1e200-d503-11eb-9611-95e78232902b.png)

2021-06-25 17:39 UTC, jruddell commented on src/app/plugins/kubernetes/components/app-catalog/helpers.ts
>    const a = versionA.split('.')
id prefer better variable names, something that reads a comparison between one version to another. Like a baseVersion and a compareVersion so you know which version is being compared. Implicitly understanding that the first argument is the base one isn't a good pattern and the variables aren't helping clarify the roles.

2021-06-25 17:42 UTC, jruddell commented on src/app/plugins/kubernetes/components/app-catalog/helpers.ts
> + * Ex. compareVersions("1.19.6-pmk.1625", "1.20.5-pmk.1831") returns -1
shouldn't you sanitize the version string to remove all characters except numbers and `.`'s? I'd be concerned this doesn't work all the time because you are losing the patch version in the `parseInt` call.

2021-06-25 17:50 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/profile-engine.tsx
> +  const [showCheckbox, setShowCheckbox] = useState(false)
I'd rather not use state here, this sets up a dependency of tracking state to wizard context, we may end up rehydrating a wizard context in the future which could potentially create issues. I would rather just read the k8s version to determine if you render or not. 

```
// assuming you change the function per my last comment to have named parameters
const showCheckbox = compareVersions({baseVersion: wizardContext.kubeRoleVersion, compareVersion: '1.20'})
```

2021-06-25 17:52 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/profile-engine.tsx
> +    if (!wizardContext.kubeRoleVersion) return
if the user can deselect the k8s version (i don't remember if they can), you will probably need to `setWizardContext({ enableProfileAgent: false })` here instead of just returning

2021-06-25 17:54 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/custom.tsx
> +const configStepAddOns = ['etcdBackup', 'prometheusMonitoringEnabled', 'enableCAS', 'profileEngine']
lets keep the naming convention the same as what backend has. `profileAgent`

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
> +const configStepAddOns = ['etcdBackup', 'prometheusMonitoringEnabled', 'enableCAS', 'profileEngine']
profileAgent

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-multi-master.tsx
> +  'profileEngine',
profileAgent

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-single-master.tsx
> +  'profileEngine',
profileAgent

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-multi-master.tsx
> +  'profileEngine',
profileAgent

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-single-master.tsx
> +  'profileEngine',
profileAgent

2021-06-25 17:55 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/cluster-addon-manager.tsx
> +  profileEngine: {
profileAgent

2021-06-25 17:56 UTC, jruddell requested changes
few minor changes

2021-06-25 21:05 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/profile-engine.tsx
> +    if (!wizardContext.kubeRoleVersion) return
Nope, the user can't deselect it

2021-06-28 20:13 UTC, jruddell approved these changes

2021-06-30 18:20 UTC, merged