[WIP] - Edit cluster page
platform9/pf9-ui-plugin pull request #1121
Opened 2021-07-13 20:03 UTC by knnguy

### WORK IN PROGRESS: Switching laptops so needed to save my work on here

2021-07-20 17:17 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/clusterAddons/helpers.ts
> +    MetallbIpRange: 'metallbCidr',
its a little strange to have the casing of this field start with a capital letter and the others dont. Is there a reason for this?

2021-07-20 17:33 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/clusterAddons/helpers.ts
> +  apiVersion: 'sunpike.platform9.com/v1alpha2',
there is a lot of repetition here related to creating these request bodies. Can we make a method that defines the overall structure of this payload and then let each of these methods pass more specifics that are different?

2021-07-20 17:33 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/clusterAddons/helpers.ts
> +    MetallbIpRange: 'metallbCidr',
Not sure, but that's how it is in the docs. 

https://platform9.atlassian.net/wiki/spaces/eng/pages/2370371762/Supported+ClusterAddon+objects

![Screen Shot 2021-07-20 at 10 32 42 AM](https://user-images.githubusercontent.com/23369276/126369521-c9d9473d-e574-40ec-9611-24c47a357028.png)

2021-07-20 17:39 UTC, jruddell commented on src/api-client/Qbert.ts
> +    name: addon.metadata?.name,
what is the need for uplifting the name and the id on each addon here? why not just do it in the selector? (I'm thinking the extra loop over all items is unnecessary)

2021-07-20 17:42 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/coreDns.tsx
> +  const { params = {}, updateParams }: { params: any; updateParams: any } = useContext(
Is this addon only used in edit cluster?

2021-07-20 19:26 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.tsx
> +    <EditClusterContext.Provider value={{ params, updateParams }}>
why do we need an edit cluster context? I feel like using a wizard here would be appropriate, and would also simplify the different places where you need to check for values in both the wizard and the edit cluster contexts.

2021-07-20 19:27 UTC, jruddell requested changes
Few things to clean up

2021-07-20 20:55 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/coreDns.tsx
> +  const { params = {}, updateParams }: { params: any; updateParams: any } = useContext(
Yes. It's automatically installed at cluster creation.

2021-07-20 22:45 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.tsx
> +    <EditClusterContext.Provider value={{ params, updateParams }}>
I did try taking out `useParams` and use `wizardContext` instead,  but it doesn't work because I can't use `setWizardContext` outside of the `render() `method. 

In the code, after the existing cluster addons are loaded, I loop through the addons in a `useEffect` hook and add their params to the form using `updateParams`. I can't do that with `setWizardContext`. I can set the form value, but I can't get it in `wizardContext`

2021-07-20 22:46 UTC, knnguy commented on src/api-client/Qbert.ts
> +    name: addon.metadata?.name,
The `id` is used as the `uniqueIdentifier` in `clusterAddonActions`

2021-07-21 12:47 UTC, mayuresh108 commented
@knnguy Maybe this is already fixed but we don't want to show these addon override params for older clusters like 1.17, 1.18 etc. 
The presence of `ClusterAddon` object for this cluster should confirm that the underlying pf9-kube version support addon mgmt.

Also the additionalDnsConfig parameter is optional, do we want to add that in the default value so it becomes clear.

2021-07-21 16:59 UTC, knnguy commented
> @knnguy Maybe this is already fixed but we don't want to show these addon override params for older clusters like 1.17, 1.18 etc.
> The presence of `ClusterAddon` object for this cluster should confirm that the underlying pf9-kube version support addon mgmt.
> 
> Also the additionalDnsConfig parameter is optional, do we want to add that in the default value so it becomes clear.

@mayuresh108 From what I'm told, users can only edit the cluster addons if the kubernetes version is 1.20 or later. The Cluster Addons part in the edit cluster page will not appear.

2021-07-21 22:48 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/clusterAddons/helpers.ts
> +    MetallbIpRange: 'metallbCidr',
Ok then leave it as is

2021-07-22 00:40 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.tsx
> +    <EditClusterContext.Provider value={{ params, updateParams }}>
I might be missing something but what about using the ValidatedForm context for everything? The values should have been added to the ValidatedForm context automatically anyways when adding components that are using the `withFormContext` HoC

2021-07-22 10:17 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.tsx
> +                  <WizardStep stepId="updateCluster">
I don't get why we have to use the Wizard even when there's only one step

2021-07-28 22:10 UTC, jruddell approved these changes

2021-07-28 22:42 UTC, merged