Added drift analysis to deployment workflow and drift analytics tab
platform9/pf9-ui-plugin pull request #1124
Opened 2021-07-16 09:07 UTC by kevinylee1991

2021-07-20 20:17 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/actions.ts
> +  const clusterId = cluster[0].uuid
if `cluster` is an array it should be plural. Can we just send the one cluster though instead of an array with one item in it?

2021-07-20 20:20 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
> +      {cluster?.length && cluster[0] && (
you can consolidate this with a single check `!!cluster?.[0] && (`

2021-07-20 20:21 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
> +    if (!!wizardContext?.cluster?.[0] && !wizardContext.cluster[0].hasBinding) {
I feel like it would be easier to just store the cluster record on the wizardContext instead of an array with one item in it, unless I'm missing something. Can you explain the reasoning for this data model?

2021-07-20 20:36 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/dry-run-dialog.tsx
> +  const getUpdate = useCallback(async () => {
I wrote a component that will poll at a given interval. why not just use that?

2021-07-20 20:43 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/cluster-role-analysis.tsx
> +  console.log(clusterRoleAnalysis)
remove console.log

2021-07-20 20:44 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/drift-analysis-result.tsx
> +      profileName: wizardContext.profile[0].name,
if profile is an array please make it plural.

2021-07-20 20:46 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/drift-analysis.tsx
> +const validJsonOrEmpty = (string) => {
try to avoid using `string` as a variable name. Its technically not a protected word but some IDE's might color code that differently because it thinks its a type.

2021-07-20 20:46 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/drift-analysis.tsx
> +    const parsedValue = JSON.parse(string)
just return it `return JSON.parse(inputValue)`

2021-07-20 20:52 UTC, jruddell requested changes
There is a lot of duplicated code here. for instance `const opIcons = {` is defined in 4 separate files. A number of things are identical between these files. If there are going to be differences then maybe we have a helper file that defines some of the shared items, like an icon mapping, custom validators... etc.

2021-07-20 22:44 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
> +    if (!!wizardContext?.cluster?.[0] && !wizardContext.cluster[0].hasBinding) {
ListTableField component stores the values in an array -- implementation is similar to the ListTable

2021-07-21 00:21 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/cluster-role-analysis-dialog.tsx
> +const renderGroupResources = (group, rbac) => {
Redeclare this as a react component if you want to use hooks here (such as `useStyles`)

2021-07-21 00:21 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/role-analysis-dialog.tsx
> +const renderGroupResources = (group, rbac) => {
This should be redeclared as a component

2021-07-21 00:21 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/role-analysis-dialog.tsx
> +    <div className={classes.resourcesList}>
Add a `key` prop here

2021-07-21 00:21 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
> +const renderProfileCalloutFields = (cluster) => (fields) => {
Maybe `moize` here to prevent creating a new function every time

2021-07-21 00:21 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/cluster-role-analysis.tsx
> +  const clusterRoleAnalysis = clusterRoles.map((clusterRole) => {
`useMemo` here

2021-07-21 01:51 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/dry-run-dialog.tsx
> +  const getUpdate = useCallback(async () => {
Looks like using PollingData works more easily for collections, but has some difficulty with calling a custom API and custom processing

2021-07-21 22:45 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/dry-run-dialog.tsx
> +  const getUpdate = useCallback(async () => {
Its just a callback function, you can define anything you want there. meaning `<PollingData reload={anyCallbackFunctionIWant}`

2021-07-21 22:46 UTC, jruddell approved these changes

2021-07-21 23:52 UTC, merged