UX-1085, UX-1136/Deployments Overview Page
platform9/pf9-ui-plugin pull request #1188
Opened 2021-08-26 17:32 UTC by knnguy

![Screen Shot 2021-08-26 at 12 18 26 PM](https://user-images.githubusercontent.com/23369276/131022981-0d169011-6684-4469-87fa-8957c9f18cdd.png)

![Screen Shot 2021-08-26 at 12 41 49 PM](https://user-images.githubusercontent.com/23369276/131026598-8843d2bb-5846-40cb-b5a6-827d6e568823.png)

![Screen Shot 2021-08-26 at 12 17 32 PM](https://user-images.githubusercontent.com/23369276/131022874-78b81809-9774-4736-aa0d-b0a8da654fcc.png)

![Screen Shot 2021-08-26 at 12 15 55 PM](https://user-images.githubusercontent.com/23369276/131022830-b8f515e9-ccc5-4e26-8d07-20e47a9198ec.png)

2021-09-01 19:25 UTC, jruddell commented on src/app/core/utils/routes.ts
> +      url: `${pluginRoutePrefix}/workloads/deployments/:id/overview/`,
generally i dont think we leave a trailing slash at the end of our urls `/:id/overview`

2021-09-01 20:21 UTC, jruddell commented on src/app/plugins/kubernetes/components/deployments/selectors.ts
> +          const allClusters = [...clusters, ...importedClusters]
you dont need to create this const every time you map a deployment, just do it once outside of the return. And better yet convert it to an object with the uuid as the key to just simply lookup a cluster by its uuid. we have an all clusters selector, you could make one that presents it in an object format for all clusters and then use that here.

2021-09-01 20:22 UTC, jruddell commented on src/app/plugins/kubernetes/components/ingresses/helpers.ts
> +export const getResourceIngresses = (services = [], ingresses = []) => {
`moize` these helpers please

2021-09-01 20:25 UTC, jruddell commented on src/app/plugins/kubernetes/components/ingresses/helpers.ts
> +  const serviceNames = pluck('name', servicesList)
lets use objects / maps more frequently for these kind of lookup items. this way we dont have to do a `find(find(includes()))`

2021-09-01 20:34 UTC, jruddell commented on src/app/plugins/kubernetes/components/services/helpers.ts
> +      !Object.entries(labels).find(
why do you need to convert this to an array and then search it? An object gives you a direct lookup that is O(1), so shouldn't this suffice?
```
const labelsMatchSelector = (labels = {}, selector = {}) => {
  if (isEmpty(labels) || isEmpty(selector)) {
    return false
  }
  for (const [selectorKey, selectorValue] of Object.entries(selector)) {
    if (labels.hasOwnProperty(selectorKey) && labels[selectorKey] === selectorValue) {
      continue
    } else {
      return false
    }
  }
  return true
} 
```

2021-09-01 20:35 UTC, jruddell commented on src/app/plugins/kubernetes/components/services/helpers.ts
> +export const getServicesForResource = (resource = {}, services = []) => {
`moize` these as well please

2021-09-01 20:38 UTC, jruddell commented on src/app/utils/misc.js
> +export const calculateAge = (creationTimestamp) => {
`moize`

2021-09-01 20:42 UTC, jruddell requested changes
Few places we can optimize, lets get this addressed and merged so we can work off of this for storage classes (sync with @rajshekhar23 on this) and for pods work.

2021-09-02 00:05 UTC, knnguy commented on src/app/plugins/kubernetes/components/common/persistent-volume-claims/helpers.tsx
> +export const getPvcs = (pods = [], allPersistentVolumeClaims = []) => {
Turns out I didn't use the function at all. Decided to map pvs to pods instead of pods to pvcs

2021-09-02 21:30 UTC, jruddell approved these changes

2021-09-02 21:40 UTC, merged