UX-1083/Updated Kubevirt New VM wizard
platform9/pf9-ui-plugin pull request #1201
Opened 2021-09-04 01:24 UTC by kevinylee1991

<img width="1594" alt="Screen Shot 2021-09-03 at 6 14 31 PM" src="https://user-images.githubusercontent.com/6668478/132077811-610439ec-c9c0-4f45-9f66-f2e32ce7c474.png">
<img width="1596" alt="Screen Shot 2021-09-03 at 6 14 39 PM" src="https://user-images.githubusercontent.com/6668478/132077813-b12b1389-65e7-49f3-ac08-93ac4fc57aea.png">
<img width="1592" alt="Screen Shot 2021-09-03 at 6 14 48 PM" src="https://user-images.githubusercontent.com/6668478/132077815-6ed15747-835c-4d0b-ad5b-de556539fda8.png">
<img width="1298" alt="Screen Shot 2021-09-03 at 6 15 10 PM" src="https://user-images.githubusercontent.com/6668478/132077817-80551141-d027-491d-872e-f51dc513ecb6.png">
<img width="1299" alt="Screen Shot 2021-09-03 at 6 15 18 PM" src="https://user-images.githubusercontent.com/6668478/132077818-b71f2f1e-ffa0-42fa-93cc-2c7c3cb9bc28.png">
<img width="1333" alt="Screen Shot 2021-09-03 at 6 15 24 PM" src="https://user-images.githubusercontent.com/6668478/132077820-57161b2c-bebe-44ef-87fc-56c57a90e2ca.png">
<img width="1229" alt="Screen Shot 2021-09-03 at 6 15 34 PM" src="https://user-images.githubusercontent.com/6668478/132077821-77bb585a-bed6-421b-bf11-7332dfbbe0f2.png">
<img width="1273" alt="Screen Shot 2021-09-03 at 6 15 47 PM" src="https://user-images.githubusercontent.com/6668478/132077823-c2d0c228-3074-4aa7-acb1-99298b8015ce.png">
<img width="1367" alt="Screen Shot 2021-09-03 at 6 16 26 PM" src="https://user-images.githubusercontent.com/6668478/132077824-fa182b7f-7859-4fd0-8aed-34da3d0d18d4.png">
<img width="1322" alt="Screen Shot 2021-09-03 at 6 16 37 PM" src="https://user-images.githubusercontent.com/6668478/132077825-4fa8460f-0bfe-4b74-b367-71c30c1cf447.png">
<img width="1334" alt="Screen Shot 2021-09-03 at 6 16 57 PM" src="https://user-images.githubusercontent.com/6668478/132077826-4b477823-3d5d-4bfc-885c-4257da930980.png">
<img width="1518" alt="Screen Shot 2021-09-03 at 6 17 35 PM" src="https://user-images.githubusercontent.com/6668478/132077827-116c6772-2e05-45e4-b2a3-0248b74db11a.png">
<img width="1298" alt="Screen Shot 2021-09-03 at 6 21 24 PM" src="https://user-images.githubusercontent.com/6668478/132077829-07532916-691b-4d9c-990c-9c0dc8f8872e.png">
<img width="1340" alt="Screen Shot 2021-09-03 at 6 21 35 PM" src="https://user-images.githubusercontent.com/6668478/132077832-fbdfab7e-2fed-4c8c-94d0-dc4746383af2.png">
<img width="1339" alt="Screen Shot 2021-09-03 at 6 21 42 PM" src="https://user-images.githubusercontent.com/6668478/132077835-c6679abb-0f9d-4d43-bf43-d390c439f349.png">
<img width="1286" alt="Screen Shot 2021-09-03 at 6 21 49 PM" src="https://user-images.githubusercontent.com/6668478/132077836-64502d8e-02ff-45de-83de-ffc2fcbfc3c0.png">
<img width="1411" alt="Screen Shot 2021-09-03 at 6 22 05 PM" src="https://user-images.githubusercontent.com/6668478/132077838-33d86554-36ab-4cf9-a668-34563ed87f7a.png">
<img width="1586" alt="Screen Shot 2021-09-03 at 6 22 11 PM" src="https://user-images.githubusercontent.com/6668478/132077839-c7dccc7f-6866-409f-a666-d2cb88cba7b5.png">

2021-09-04 20:37 UTC, jruddell commented on src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
> +import React, { useEffect } from 'react'
this page has been reworked, what changes did you apply to this page? we moved it to typescript so you're re-adding the same page as javascript now

2021-09-04 20:40 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/actions.ts
> +export const pvcsLoader = createContextLoader(
can you work with kim and raj on this? there's already been work done around loading pvcs. We should consolidate under one action so we dont have conflicts

2021-09-04 20:45 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/basic-step.tsx
> +                            ...wizardContext.vmNames.slice(0, idx),
why not just use splice to insert at an index `[...wizardContext.vmNames].splice(idx, 0, value)`

2021-09-04 20:47 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/helpers.ts
> +  if (disk?.sourceType === 'httpUrl') {
this is a bit sloppy. Can you use a more functional way to do this? I think it'll clean it up a lot and reduce the if else madness

2021-09-04 20:49 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/helpers.ts
> +export const getVolumeJson = (wizardContext) => {
should memoize this function and also pull out the specific fields you need from wizard context as individual params so the memoize can be effective

2021-09-04 20:52 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/storage-step.tsx
> +  const [dataVolumes, loading] = useDataLoader(dataVolumesLoader, {
since you're already adding as any at the end of this data loader, you should also use typings here `const [dataVolumes, loading]: IUseDataLoader<DataVolumeTypeHere> = useDataLoader(..., ...) as any`

2021-09-04 20:53 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/storage-step.tsx
> +    [wizardContext, setWizardContext],
instead of depending on the whole wizard context, just reference a specific value inside it, this will make these memoizers much more effective.

2021-09-04 20:56 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/storage-step.tsx
> +      setWizardContext({
another place to just use splice instead. 
```
setWizardContext({
  storageDisks: [ ...wizardContext.storageDisks ].splice(idx, 0, {
    ...wizardContext.storageDisks[idx],
    ...value,
  })
})
```

2021-09-04 21:07 UTC, jruddell requested changes
Few things you need to address, also, why are we adding new icon files? I think we've standardized on using fontawesome icons (Image loading is more overhead that we can avoid). There should be an equivalent icon in fa that you see on the designs.

2021-09-07 16:50 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
> +import React, { useEffect } from 'react'
ah okay, i'll check on this I didn't notice a conflict when I pulled in master

2021-09-07 16:53 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/virtual-machines/actions.ts
> +export const pvcsLoader = createContextLoader(
oh I actually have this finished when I was checking out of the merged code was working. I will push those fixes I caught right now to this PR

2021-09-07 17:20 UTC, anmolsachan commented
<img width="1586" alt="132077839-c7dccc7f-6866-409f-a666-d2cb88cba7b5" src="https://user-images.githubusercontent.com/8753636/132383372-07f644b7-3d4c-4a49-be17-43114fec8ee9.png">

As someone who saw this for the first time, when I saw the column Age(which makes complete sense from Admin/Devs perspective), I was expecting the humanize form like 5 hours, 4 minutes, 3seconds, and below that the actual timestamp could be mentioned.  Or there could be 2 separate columns for Timestamp and Age. Just a suggestion.

Age

5 hours, 4 minutes, 3seconds
Created At: 09/03/2021, 5:47 PM

2021-09-07 23:38 UTC, jruddell commented
> As someone who saw this for the first time, when I saw the column Age(which makes complete sense from Admin/Devs perspective), I was expecting the humanize form like 5 hours, 4 minutes, 3seconds, and below that the actual timestamp could be mentioned. Or there could be 2 separate columns for Timestamp and Age. Just a suggestion.
> 
> Age
> 
> 5 hours, 4 minutes, 3seconds
> Created At: 09/03/2021, 5:47 PM

I think it would be better to surface that information underneath a tooltip on hover vs persistent. This date format is used in many places and that may not fit well on those other views.

2021-09-08 05:10 UTC, anmolsachan commented
> > As someone who saw this for the first time, when I saw the column Age(which makes complete sense from Admin/Devs perspective), I was expecting the humanize form like 5 hours, 4 minutes, 3seconds, and below that the actual timestamp could be mentioned. Or there could be 2 separate columns for Timestamp and Age. Just a suggestion.
> > Age
> > 5 hours, 4 minutes, 3seconds
> > Created At: 09/03/2021, 5:47 PM
> 
> I think it would be better to surface that information underneath a tooltip on hover vs persistent. This date format is used in many places and that may not fit well on those other views.

Makes sense. Thanks for the info. :smiley:

2021-09-08 17:02 UTC, jruddell commented
> > > As someone who saw this for the first time, when I saw the column Age(which makes complete sense from Admin/Devs perspective), I was expecting the humanize form like 5 hours, 4 minutes, 3seconds, and below that the actual timestamp could be mentioned. Or there could be 2 separate columns for Timestamp and Age. Just a suggestion.
> > > Age
> > > 5 hours, 4 minutes, 3seconds
> > > Created At: 09/03/2021, 5:47 PM
> > 
> > 
> > I think it would be better to surface that information underneath a tooltip on hover vs persistent. This date format is used in many places and that may not fit well on those other views.
> 
> Makes sense. Thanks for the info. 😃

Yep! Thanks for the recommendation! definitely a nice thing to surface around these dates. We have moment so we could use `fromNow()` as well

2021-09-08 20:08 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/virtual-machines/add/basic-step.tsx
> +                            ...wizardContext.vmNames.slice(0, idx),
splice edits the original object but let me know if you like the implementation better

2021-09-10 01:45 UTC, kevinylee1991 commented
<img width="1594" alt="Screen Shot 2021-09-09 at 6 31 57 PM" src="https://user-images.githubusercontent.com/6668478/132785456-11f4630c-8d67-4fb0-89b4-756801bf2901.png">
<img width="1596" alt="Screen Shot 2021-09-09 at 6 32 19 PM" src="https://user-images.githubusercontent.com/6668478/132785458-b70456f3-687c-42d7-8759-516f10aec102.png">
<img width="1594" alt="Screen Shot 2021-09-09 at 6 44 32 PM" src="https://user-images.githubusercontent.com/6668478/132785460-bd49f282-7fa3-4eeb-9bfa-112be28b0ed4.png">

2021-09-10 22:05 UTC, jruddell commented on src/api-client/Qbert.ts
> +    const data = await this.client.basicGet<any>({
instead of any types, can you use the autogenerator to create types based on the return of these api calls? follow the convention of putting a model in a `model` file where the component is please

2021-09-10 22:09 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/add.tsx
> +import React, { useCallback, useMemo } from 'react'
rename this to `index.tsx`

2021-09-10 22:17 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/add/storage-step.tsx
> +      storageDisks.splice(idx, 1, {
`splice` mutates the original array. make sure you are making a copy of storage disks before calling splice `const storageDisks = [...wizardContext.storageDisks]`

2021-09-10 22:21 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/selectors.ts
> +    clustersSelector,
you can use the all cluster selector here, or better yet use the `defaultAllClustersSelector` variable i've exported

2021-09-10 22:22 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/virtual-machine-power-operation-dialog.tsx
> +          <Button variant="outlined" color="secondary" onClick={onClose}>
dont use material-ui for elements that we have our own for. We will be getting rid of material ui in the near future.

2021-09-10 22:25 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/vmi-power-operation-dialog.tsx
> +const capitalizeFirstLetter = (string = '') => {
we have a helper method `capitalizeString` that does this I believe

2021-09-10 22:25 UTC, jruddell commented on src/app/plugins/kubernetes/components/virtual-machines/vmi-power-operation-dialog.tsx
> +          <Button variant="outlined" color="secondary" onClick={onClose}>
`/core/elements/button`

2021-09-10 22:26 UTC, jruddell approved these changes
some minor fixes, after that lets get this merged

2021-09-10 23:51 UTC, merged