UX-1142/Added monitoring addon and some refactoring and cleanup
platform9/pf9-ui-plugin pull request #1223
Opened 2021-09-14 19:55 UTC by xantorres

2021-09-14 20:13 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
> +        getAddonVersions(cluster.uuid),
I have refactored all of these to not be tied to cluster loading. Can we move the getAddonVersions call to the view that actually consumes this data?

2021-09-14 20:17 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/helpers.ts
> +      [ClusterAddonType.Monitoring]: '0.46.0',
in 5.4 I believe the api to get addon versions can replace this hardcoded mapping

2021-09-14 20:18 UTC, jruddell requested changes
few comments to resolve

2021-09-14 20:33 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/auto-scaling.tsx
> +  <CheckboxField
Shoudn't this be the AddonCheckbox component instead?

2021-09-14 20:57 UTC, knnguy requested changes

2021-09-14 20:57 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/auto-scaling.tsx
> +  <CheckboxField
I also noticed that `AddonCheckbox` and `AddonFields` were not used for `EtcdBackup` and `MetalLb` addons

2021-09-14 20:57 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/helpers.ts
> +  ClusterAddonType.AzureAutoScaler,
This should be `ClusterAddonType.AwsAutoScaler`

2021-09-14 21:00 UTC, knnguy commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/auto-scaling.tsx
> +  <CheckboxField
This should be using `CheckboxAddon`, right?

I noticed that `CheckboxAddon` and `AddonFields` weren't used for MetaLb and EtcdBackup addons

2021-09-14 21:28 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/auto-scaling.tsx
> +  <CheckboxField
I didn't use that there (yet) because there was some extra logic there and also some addons were not defined in `ClusterAddonType` for some reason.

2021-09-16 17:27 UTC, jruddell commented on src/app/plugins/kubernetes/DataKeys.ts
> +  AddonVersions = 'AddonVersions',
make sure to define a human readable name for this data key in the mapping above

2021-09-16 17:32 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/actions.ts
> +import { ActionDataKeys } from 'k8s/DataKeys'
why switch to the JS data keys in a TS file?

2021-09-16 17:49 UTC, jruddell approved these changes

2021-09-16 17:52 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-addons/actions.ts
> +import { ActionDataKeys } from 'k8s/DataKeys'
Oops, sorry

2021-09-16 19:28 UTC, knnguy approved these changes

2021-09-16 19:57 UTC, merged