Add tests for user section
platform9/pf9-ui-plugin pull request #1228
Opened 2021-09-16 06:56 UTC by hgupta2363

1 test cases for create new user

2 test cases for edit user

3 test cases for delete user

2021-09-16 18:08 UTC, jruddell commented on cypress/integration/deleteUser.spec.ts
> +describe('delete tenant', () => {
The names of your tests here say `tenant` but they are about a `user`.

2021-09-16 18:08 UTC, jruddell commented on cypress/integration/editUser.spec.ts
> +describe('delete tenant', () => {
tenant instead of user

2021-09-16 18:09 UTC, jruddell requested changes
Fix the test names please

2021-09-22 18:38 UTC, jruddell commented on cypress/integration/deleteUser.spec.ts
> +    cy.visit('/ui/my-account/user_management#users')
if its possible to use our routes for this that would be preferred

2021-09-22 18:42 UTC, jruddell commented on cypress/integration/deleteUser.spec.ts
> +    cy.getByTestId('delete-title')
I don't like `delete-title`, can you make this be something more specific as to what it is deleting?

2021-09-22 18:43 UTC, jruddell commented on src/app/plugins/account/components/userManagement/users/delete-user-dialog.tsx
> +      <DialogTitle data-testid={generateTestId('delete', 'title')}>
maybe add `user` in the test-id?

2021-09-22 18:44 UTC, jruddell requested changes
Few things to tweak. Check the titles of your test suites. I see a lot of `describe('tenant ...` inside user specs.

2021-09-28 06:48 UTC, jruddell commented on cypress.example.json
> +    "deleteTenant.spec.ts",
this is an example file, you probably shouldn't be making changes here

2021-09-28 06:51 UTC, jruddell commented on src/app/plugins/account/components/userManagement/users/EditUserPage.js
> +      <SimpleLink className={classes.togglableFieldBtn} onClick={toggleField} label={label}>
why do we need to add a prop to SimpleLink here? can't you just use the children?

2021-09-28 09:20 UTC, hgupta2363 commented on src/app/plugins/account/components/userManagement/users/EditUserPage.js
> +      <SimpleLink className={classes.togglableFieldBtn} onClick={toggleField} label={label}>
children is same for all fields like usename,password so if we use only children to generate testid then multiple fields will have same testid

2021-09-28 21:08 UTC, jruddell commented on src/app/plugins/account/components/userManagement/users/EditUserPage.js
> +      <SimpleLink className={classes.togglableFieldBtn} onClick={toggleField} label={label}>
children is the text content for SimpleLink. what makes label unique? SimpleLink is used in many places in the application, are we going to add a label to each time we render it?

2021-09-29 04:57 UTC, hgupta2363 commented on src/app/plugins/account/components/userManagement/users/EditUserPage.js
> +      <SimpleLink className={classes.togglableFieldBtn} onClick={toggleField} label={label}>
label has more specific info about textfield children value is "change" which is same for each textfield and I don't think we need to pass label prop in every SimpleLink render because here only multiple textfield is sharing single simpleLink render

2021-10-04 13:13 UTC, kingshuk-nandy commented on cypress/integration/users/createUser.spec.ts.ts
> +    cy.wait(4000)
Same as above. Try avoid using hardcoded wait

2021-10-14 05:55 UTC, merged