Ux-1516: Updated all material ui <Switch> references with <ToggleSwitch>
platform9/pf9-ui-plugin pull request #1432
Opened 2022-01-11 17:13 UTC by patil-pratik-87

<img width="899" alt="Screenshot 2022-01-11 at 9 27 59 PM" src="https://user-images.githubusercontent.com/63217589/148989363-1cf96659-c25d-40ae-901a-0f5ef2c12f25.png">
<img width="832" alt="Screenshot 2022-01-11 at 9 28 08 PM" src="https://user-images.githubusercontent.com/63217589/148989374-4b018f18-6116-4d6f-9951-4f540115d047.png">
<img width="572" alt="Screenshot 2022-01-11 at 10 40 01 PM" src="https://user-images.githubusercontent.com/63217589/148989377-5f4c33e1-54f7-49c9-af94-405d9b464b99.png">

2022-01-11 19:18 UTC, jruddell requested changes
Make sure there is a space between the two switches inside cluster upgrade

2022-01-12 03:28 UTC, jruddell approved these changes

2022-01-12 03:58 UTC, patil-pratik-87 commented
> Make sure there is a space between the two switches inside cluster upgrade

It is

2022-01-12 04:02 UTC, patil-pratik-87 commented
> Make sure there is a space between the two switches inside cluster upgrade

I have added it already. just uploaded the wrong screenshot 😁

2022-01-12 06:37 UTC, closed without merging