UX-1524: Removed prettier + Eslint as the primary format tool + Fixed…
platform9/pf9-ui-plugin pull request #1460
Opened 2022-01-24 14:23 UTC by patil-pratik-87

Removed prettier as in its latest version it was extremely opinionated and did not provide us with the flexibility to tweak the rules we wanted. Hence, we decided to remove it and rely on eslint for formatting as well.

Comments here -> https://github.com/platform9/pf9-ui-plugin/pull/1455 are addressed in this PR.
This is a new branch incorporating the removal of prettier. New branch as it made more sense rather than fixing each unwanted prettier format manually.

Changes:-
Updated linting plugins and configs in .eslintrc.
Updated specific rules in .eslintrc.
Removed prettier completely.
Fixed the pre-commit hook to format and lint successfully before committing.

Note -->
- Still, we have a lot of warnings in linting. Some of them might be legitimate errors. Feel free to change the rules to throw errors and fix the issues if you feel so.

- I suggest you turn on the Eslint extension of the vscode and add

**"editor.codeActionsOnSave": { 
"source.organizeImports": false, 
"source.fixAll.eslint": true }, 
"editor.formatOnSave": true,**              in your settings.json in vscode to quick fix the formatting issues in the editor.

- Disable/Remove **Prettier** extension from vscode.
- 
I surely might have made some errors while fixing the issues. Let me know what I broke :) and I will fix it.

Let me know if you find something weird in the application :)

I see the compilation and lining green at this stage.

2022-01-24 14:31 UTC, xantorres approved these changes

2022-01-24 17:14 UTC, jruddell requested changes
Unfortunately were not going to be able to remove prettier. For now we should just stick on an older version that honors our code style and isn't as opinionated. the point here is devs shouldn’t care about code style. It should just work. And if we dont have something that will consistently format everything we will expose a number of issues that will reduce dev productivity

2022-01-25 04:56 UTC, patil-pratik-87 commented
> Unfortunately were not going to be able to remove prettier. For now we should just stick on an older version that honors our code style and isn't as opinionated. the point here is devs shouldn’t care about code style. It should just work. And if we dont have something that will consistently format everything we will expose a number of issues that will reduce dev productivity

Yeah, after our discussion, moved to the older version

2022-01-25 06:05 UTC, jruddell approved these changes

2022-01-25 06:06 UTC, jruddell commented
Looks great! thanks for taking the initiative here @patil-pratik-87

2022-01-25 06:18 UTC, merged