UX-1402/Default to the newest kubernetes version when creating a cluster
platform9/pf9-ui-plugin pull request #1487
Opened 2022-02-01 06:08 UTC by Nalinmujoo

The field is pre-filled with the newest Kubernetes version.
<img width="370" alt="Screenshot 2022-02-01 at 11 31 45 AM" src="https://user-images.githubusercontent.com/31595960/151920619-2fa151ed-f7b3-4905-857b-bfa125477632.png">

The options are sorted in descending order by version (newest first).
<img width="360" alt="Screenshot 2022-02-01 at 11 32 01 AM" src="https://user-images.githubusercontent.com/31595960/151920665-6c8fbe50-ba70-43ca-b1b9-f0d5a6ba527a.png">

2022-02-01 06:43 UTC, patil-pratik-87 approved these changes

2022-02-01 18:10 UTC, jruddell commented on src/app/plugins/kubernetes/components/common/kubernetes-version-picklist.tsx
> +      roles.sort((a, b) => compareVersions(b.roleVersion, a.roleVersion)) //sort in descending order
I dont think we should be sorting the array here, this will mutate the array as well. Instead lets keep it in asc order, but just pick the latest / highest value as the default selection.

2022-02-01 18:11 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/kubernetes-version.tsx
> +      selectFirst={true}
you don't need to explicitly set `true`, if you set `selectFirst` implicitly it will be true

2022-02-01 18:12 UTC, jruddell commented on src/app/plugins/kubernetes/components/common/kubernetes-version-picklist.tsx
> +        selectFirst = false
This is assigning a value to a prop which is an anti-pattern in React. What is the reason for doing this? help explain the goal and I can help rejigger things for you

2022-02-01 20:32 UTC, jruddell requested changes
Please address the review comments before moving forward

2022-02-02 17:51 UTC, jruddell approved these changes

2022-02-02 17:51 UTC, merged