Updated RBAC profile and drift analysis pages to use new actions
platform9/pf9-ui-plugin pull request #1606
Opened 2022-03-17 00:42 UTC by kevinylee1991

2022-03-18 03:19 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +const RenderClusters = ({ value }) => {
would the generic grid array cell work here?

2022-03-18 03:22 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +export const RenderStatus = ({ value }) => {
can we use our badge status here? What is the purpose of this unique status presentation?

2022-03-18 18:09 UTC, xantorres requested changes

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +        handleAction: (selectedItems) => {
you could do `([firstSelectedItem])` here

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/create/BaseClusterForm.tsx
>      healthyClusters: true,
This should have been defined in the `defaultParams` object

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/deploy/SelectClusterForm.tsx
> +const defaultParamsClusterSelector = makeParamsClustersSelector()
Put a `{ healthyClusters: true }` so you don't need to do do it later and you can just use `useSelector(defaultParamsClusterSelector)`

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/ClusterProfileSelection.tsx
> +const renderTypes = (_, profile) => <TypesTableCell item={profile} />
Is this still being used?

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/ClusterProfileSelection.tsx
> +const defaultParamsClusterSelector = makeParamsClustersSelector()
`{ healthyClusters: true }` here, and you can remove it below

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/DriftAnalysis.tsx
> +    <Tabs activeTab={activeTab} setActiveTab={(tab) => setActiveTab(tab)}>
`setActiveTab={setActiveTab}`

2022-03-18 18:09 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/ViewDriftAnalysisPage.tsx
> +      dryRun: true,
assign this static param in the `makeRbacProfileBindingsSelector()` call

2022-03-21 22:26 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +const RenderClusters = ({ value }) => {
hmm, it probably would if we don't mind changing the cell from a tooltip to just listing it out, but prob best to ask chris

2022-03-21 22:32 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +export const RenderStatus = ({ value }) => {
Some of the statuses are not meant to have a circle icon. Am not sure if the badge would work here

2022-03-21 22:39 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +  const { params, getParamsUpdater } = usePrefParams({})
params are still used for the column/row ordering right?

2022-03-21 23:28 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/ClusterProfileSelection.tsx
> +const renderTypes = (_, profile) => <TypesTableCell item={profile} />
Yes because this form field is still using ListTable, which passes through the values as (value, item) rather than ({ value, item })

2022-03-21 23:49 UTC, jruddell commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +export const RenderStatus = ({ value }) => {
badge is not the circle icon status. its the one on the pods list page

2022-03-22 16:01 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +  const { params, getParamsUpdater } = usePrefParams({})
Right, they are just not need for the `useListAction` below, maybe

2022-03-22 16:22 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/DriftAnalysisListPage.tsx
> +const RenderCreated = ({ value }) => <DateAndTime value={value} />
Can we rename this to `CreatedCell`  or `DateCreatedCell` please?

2022-03-22 16:26 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/drift/ClusterProfileSelection.tsx
> +    healthyClusters: true,
This should be in the `const defaultParamsClusterSelector = makeParamsClustersSelector()` above

2022-03-22 19:40 UTC, xantorres commented on src/app/plugins/kubernetes/components/rbac/profiles/DriftAnalysisListPage.tsx
> +const RenderCreated = ({ value }) => <DateAndTime value={value} />
Actually, you can use `DateAndTime` directly, just do `CellComponent: DateAndTime`

2022-03-22 21:40 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/clusters/selectors.ts
> +const clusterSelectorDefaultParams: any = {
loll i wasn't sure what a good solution to typing this was

2022-03-22 21:42 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/rbac/profiles/RbacProfilesListPage.tsx
> +  const { params, getParamsUpdater } = usePrefParams({})
oh yeah that sounds correct

2022-03-22 23:19 UTC, xantorres commented on src/app/plugins/kubernetes/components/infrastructure/clusters/selectors.ts
> +const clusterSelectorDefaultParams: any = {
Use `SortingState` from `useGridSorting` please

2022-03-23 17:27 UTC, xantorres approved these changes

2022-03-24 17:00 UTC, merged