Minor Fixes on Bareos Create Cluster
platform9/pf9-ui-plugin pull request #1737
Opened 2022-04-21 06:06 UTC by patil-pratik-87

Before :- 
<img width="744" alt="Screenshot 2022-04-20 at 10 41 17 PM" src="https://user-images.githubusercontent.com/63217589/164385195-51796042-572b-4456-8c95-6d581e48fed8.png">

After :-
 ![Screenshot 2022-04-21 at 10 39 45 AM](https://user-images.githubusercontent.com/63217589/164385190-b0ef3091-de27-464c-a9ea-c9d31a062e0f.png)

Fixed validation for when no nodes are selected for Master/Worker
![Screenshot 2022-04-21 at 11 29 20 AM](https://user-images.githubusercontent.com/63217589/164385337-399ff78b-4e40-4639-b2c9-3f41343dfc5e.png)
 Nodes

2022-04-21 08:24 UTC, jruddell commented
worker nodes are not required on a single master cluster, so we shouldn't be requiring validation on this

2022-04-21 14:25 UTC, jruddell commented
Please remove the validation changes you did. We have a validation system that checks for things. This here isn't using that. The form validation should be fine for now

2022-04-21 15:19 UTC, jruddell requested changes
Let's clean this up some, please remove the validation stuff you did. I'll show you how this stuff works on a call later. 

Styling with a * selector should be avoided on highly used components because of the excess css styling in each instance

2022-04-21 15:19 UTC, jruddell commented on src/app/core/elements/tooltip/Tooltip.tsx
> +    '& *': {
Generally styling this way is not efficient. Can we update the children to be styled correctly instead?

2022-04-22 14:44 UTC, patil-pratik-87 commented
> Please remove the validation changes you did. We have a validation system that checks for things. This here isn't using that. The form validation should be fine for now

done

2022-04-23 04:16 UTC, patil-pratik-87 commented
> Please remove the validation changes you did. We have a validation system that checks for things. This here isn't using that. The form validation should be fine for now

Yeah, we ve fixed the form validation and used that now :)

2022-04-23 04:16 UTC, patil-pratik-87 commented on src/app/core/elements/tooltip/Tooltip.tsx
> +    '& *': {
true, used more specific classes

2022-04-23 14:04 UTC, jruddell approved these changes

2022-04-24 04:08 UTC, merged