UX-1855/NodesListPage: After selecting 'No Cluster', selecting 'All' doesn't work
platform9/pf9-ui-plugin pull request #1759
Opened 2022-04-28 16:55 UTC by Nalinmujoo

After selecting 'No Cluster', selecting 'All' shows all nodes

<img width="1217" alt="Screenshot 2022-04-28 at 10 12 42 PM" src="https://user-images.githubusercontent.com/31595960/165804593-7ad2eb94-f95b-4422-8449-454e3ae65ce9.png">

<img width="1211" alt="Screenshot 2022-04-28 at 10 13 05 PM" src="https://user-images.githubusercontent.com/31595960/165804613-99be4024-c193-47a1-9f4d-bd99c67c01b9.png">

2022-04-29 05:40 UTC, patil-pratik-87 approved these changes

2022-04-29 19:47 UTC, jruddell approved these changes

2022-05-01 21:28 UTC, xantorres requested changes

2022-05-01 21:28 UTC, xantorres commented on src/app/core/elements/dropdown/Dropdown.tsx
> +    if ((showAll && isNil(value)) || value === allKey) {
this would be better as `if (showAll && (isNil(value)) || value === allKey)) {`

2022-05-01 21:28 UTC, xantorres commented on src/app/core/elements/dropdown/Dropdown.tsx
> +    if ((showNone && isNil(value)) || value === noneKey) {
same here

2022-05-02 22:35 UTC, xantorres approved these changes

2022-05-03 05:49 UTC, merged