Fixed bug with ListContainer columns where newly added columns were u…
platform9/pf9-ui-plugin pull request #1795
Opened 2022-05-19 22:44 UTC by kevinylee1991

…nable to show up on the table

To reproduce bug, try adding a new column to a table -- the new column will not show up. With this code it will update appropriately.

2022-05-21 21:55 UTC, xantorres requested changes

2022-05-24 00:59 UTC, kevinylee1991 commented on src/app/core/elements/grid/hooks/useGridManagedColumns.ts
> +      dispatch({ type: 'setVisibleColumnKeys', payload: { columnKeys: newVisibleColumns } })
makes sense, moved it into the initial values setter

2022-05-24 19:16 UTC, xantorres commented on src/app/core/elements/grid/hooks/useGridManagedColumns.ts
> +    return {
Why not just filter the `columnSpecs` here before doing anything else so you won't need to do the filtering twice afterwards?

2022-05-24 20:05 UTC, xantorres commented on src/app/core/elements/grid/hooks/useGridManagedColumns.ts
> +  const visibleKeys = columnSpecs.reduce((acc, { display = true, key }) => {
I think you could pass the already filtered `orderedColumnKeys` so that you won't have to do a symetricDifference and union again here.

2022-06-03 00:46 UTC, kevinylee1991 commented on src/app/core/elements/grid/hooks/useGridManagedColumns.ts
> +  const visibleKeys = columnSpecs.reduce((acc, { display = true, key }) => {
orderedColumnKeys gets defined at the same time together with visibleColumnKeys though and they're only called once at the start. Maybe we could store it in a variable, but because of the conditionals in the initialState useMemo, perhaps this wouldn't be all that worth it?

2022-07-06 19:16 UTC, merged