UX-2133/Added Grafana and Kubeconfig links for capi clusters on capi …
platform9/pf9-ui-plugin pull request #1953
Opened 2022-09-08 00:29 UTC by kevinylee1991

…cluster details page

I believe I have the links correct, but it's currently inaccessible, think it is a backend issue. Have posted in cluster-api channel about it.

<img width="1576" alt="Screen Shot 2022-09-07 at 5 10 10 PM" src="https://user-images.githubusercontent.com/6668478/189007632-6bea6acf-c9d1-4c0e-a3b6-f0fc1e65c3d4.png">

2022-09-08 11:10 UTC, patil-pratik-87 approved these changes

2022-09-08 11:10 UTC, patil-pratik-87 commented on src/app/plugins/infrastructure/components/clusters/capi/actions.ts
> +  // .addDependency(DataKeys.ClusterAddons),
@kevinylee1991 This was helpful for refreshing the cluster addons statuses when we refresh or poll. Is there a reason to not have this?

2022-09-09 05:50 UTC, patil-pratik-87 approved these changes

2022-09-09 05:50 UTC, patil-pratik-87 commented on src/app/plugins/infrastructure/components/clusters/capi/actions.ts
> +  // .addDependency(DataKeys.ClusterAddons),
ohh okay.

2022-09-09 10:41 UTC, patil-pratik-87 requested changes

2022-09-09 10:41 UTC, patil-pratik-87 commented on src/app/plugins/infrastructure/components/clusters/capi/helpers.ts
> +  return `${window.location.origin}${getCapiClusterProxyEndpoint(
@kevinylee1991 The change that Erwin has made needs the auth token in the form of cookies. This change will have to be made in the UI. 
For ref:- https://github.com/platform9/pf9-cluster-api/pull/270/files#diff-7fd0050121b6057009743f0050ecc35f6b97cbff89f0672e8ddca3973890d3e6R142

2022-09-09 18:03 UTC, kevinylee1991 commented on src/app/plugins/infrastructure/components/clusters/capi/helpers.ts
> +  return `${window.location.origin}${getCapiClusterProxyEndpoint(
The auth token is already in the cookies (set by token2cookie api request) so we're all good

2022-09-09 18:03 UTC, merged