Fix custom path string function in yaml template parser to handle mul…
platform9/pf9-ui-plugin pull request #2015
Opened 2022-09-13 21:21 UTC by kevinylee1991

…tiple string interpolations

2022-09-13 22:25 UTC, knnguy approved these changes

2022-09-14 13:27 UTC, xantorres requested changes

2022-09-14 13:27 UTC, xantorres commented on src/app/utils/YamlTemplateParser.ts
> +    const matches = customString.match(regex)
You could probably replace all of this function with a simple `.replace`:
`customString.replace(/\${(.*?)\}/g, (match, path) => pathStr(path, this.values) || '');`

2022-09-14 22:45 UTC, kevinylee1991 commented on src/app/utils/YamlTemplateParser.ts
> +    const matches = customString.match(regex)
oh cool thanks, this helped me learn about regex some more (my weakness lol)

2022-09-14 23:10 UTC, merged