UX-437/Modified Alert retrieval from API
platform9/pf9-ui-plugin pull request #848
Opened 2020-09-09 21:41 UTC by knnguy

Also added an 'Exported Namespace' column to the alerts table

![Screen Shot 2020-09-09 at 2 33 09 PM](https://user-images.githubusercontent.com/23369276/92657694-1b9f2c80-f2aa-11ea-86be-111ec9214f64.png)

2020-09-10 05:24 UTC, jruddell commented on src/api-client/Qbert.ts
> +        id: `${alert.labels.alertname}${clusterUuid}${alert.labels.exported_namespace}${alert.labels.severity}`,
I think we should think about how we're defining the ID. Wouldn't the alert type, clusterUuid and timestamp be enough to have a unique ID for each alert?

2020-09-10 05:25 UTC, jruddell commented on src/api-client/Qbert.ts
> +    return response.alerts.map((alert) => {
We should probably do this data mapping inside a selector

2020-09-10 10:57 UTC, xantorres requested changes

2020-09-10 10:57 UTC, xantorres commented on src/api-client/Qbert.ts
> +    const alertsFromRules = await this.getPrometheusAlertsFromRules(clusterUuid)
You can create a DataLoader from this and call it here, so that then you will be able to access it from the selectors.

2020-09-10 11:06 UTC, xantorres requested changes

2020-09-10 11:06 UTC, xantorres commented on src/api-client/Qbert.ts
> +        id: `${alert.labels.alertname}${clusterUuid}${alert.labels.exported_namespace}${alert.labels.severity}`,
We don't need this ID here, if you really want to have a `uniqueIdentifier`, you can define a composite ID when creating the action (using createCRUDActions) by passing an array of identifiers such as `uniqueIdentifier: ['alert.labels.alertname', 'clusterId', 'alert.labels.exported_namespace', 'alert.labels.severity']`.
Either way, I don't even think we should be caching these alerts, so it might be better to just add a `cache: false` option so that we don't even need to use a unique identifier.

2020-09-10 11:28 UTC, xantorres requested changes

2020-09-10 11:28 UTC, xantorres commented on src/api-client/Qbert.ts
> +        id: `${alert.labels.alertname}${clusterUuid}${alert.labels.exported_namespace}${alert.labels.severity}`,
Backend should always provide us with unique identifiers for the data, it makes no sense that we have to deal with this kind of stuff.
Either way, in this specific case we probably don't want to cache these items as they are just used in this specific instance and they are being refreshed constantly so caching doesn't make a lot of sense. So I would just get rid of the cache overall by using the new option `cache: false` when creating the action, and maybe generate a unique ID here by using `uuid.v4()` or whatever, as a workaround so that react can track the items when rendering them.

2020-09-10 22:06 UTC, jruddell commented on src/api-client/Qbert.ts
> +        id: `${alert.labels.alertname}${clusterUuid}${alert.labels.exported_namespace}${alert.labels.severity}`,
We will have future use cases like dom manipulation based on an elements ID. I'd like these ID's to be derived from the data so we can recreate these id's if needed, lets use `<alert type>-<clusterUuid>-<alert timestamp>` here. Those fields should never be empty

2020-09-11 21:57 UTC, knnguy commented
![Screen Shot 2020-09-11 at 2 56 12 PM](https://user-images.githubusercontent.com/23369276/92976317-23dca080-f43f-11ea-95d9-cfa9308f3ebe.png)

![Screen Shot 2020-09-11 at 2 56 36 PM](https://user-images.githubusercontent.com/23369276/92976322-263efa80-f43f-11ea-8e42-364109ac9473.png)

2020-09-11 22:44 UTC, jruddell commented on src/app/plugins/kubernetes/components/monitoring/actions.js
> +import ApiClient from 'api-client/ApiClient'
we have an actions file for alerts already. I believe its `/components/alarms/actions.js`. Probably better to put this action there

2020-09-11 22:53 UTC, knnguy commented on src/app/plugins/kubernetes/components/monitoring/actions.js
> +import ApiClient from 'api-client/ApiClient'
This was part of Kevin's change. I originally had the action in the alarm actions file, but Kevin added the same action in the monitoring alarms file. That's why we decided to just use the one he had. Should I copy and paste the action back into the alarm actions file as well?

2020-09-12 05:40 UTC, jruddell approved these changes

2020-09-12 05:49 UTC, merged