UX-623/Allow optional updating of cloud provider fields
platform9/pf9-ui-plugin pull request #878
Opened 2020-10-09 00:30 UTC by kevinylee1991

2020-10-09 04:29 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AwsCloudProviderFields.tsx
> +        required={optionalFields ? false : true}
you don't need a ternary operator here. `required={!optionalFields}`

2020-10-09 04:32 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
> +      key: !!data.awsAccessKey ? data.awsAccessKey : undefined,
this is a typescript file so just use the optional chaining operator. Also include it on the `name` as that should be an optional parameter on edit

```
return {
  name: data?.name,
  key: data?.awsAccessKey,
  secret: data?.awsSecretKey,
}
```

2020-10-09 04:33 UTC, jruddell requested changes
Few optimizations / cleaner code

2020-10-13 19:33 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
> +      key: !!data.awsAccessKey ? data.awsAccessKey : undefined,
I figured for the name since it gets prepopulated by the update form that it would never really be optional. I also have it as a required field still so that they don't rename their cloud provider as empty string. Thoughts?

2020-10-13 20:00 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
> +      key: !!data.awsAccessKey ? data.awsAccessKey : undefined,
I tried using data?.awsAccessKey etc. but the UI sent empty strings in the request when I filled in the fields and deleted them. Not sure if there is a good other way to set undefined.

2020-10-13 21:23 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
> +      key: !!data.awsAccessKey ? data.awsAccessKey : undefined,
you shouldn't be passing any form fields when they are empty. Someone may want to update their credentials without changing the name, or change the name without changing the credentials. If a field is empty it shouldn't be included as a key in the update call

2020-10-15 22:07 UTC, jruddell commented on src/app/core/components/wizard/Wizard.js
> +        if (steps[activeStep]?.onNext) {
this is a javascript file, this'll be a problem

2020-10-15 22:09 UTC, jruddell commented on src/app/plugins/kubernetes/components/common/CloudProviderCard.tsx
> +    <div className={clsx(classes.root, className)} onClick={handleClick}>
we shouldn't need to pass class names to these cards. use css grid to space them out (`grid-gap`)

2020-10-15 22:10 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +      showToast(err, MessageTypes.error)
instead of showing a toast can we integrate the error on the page? just like you and I did for downloading the IAM policy (I think).

2020-10-15 22:12 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AzureCloudProviderFields.tsx
> +          <Button disabled type="submit">
is this button always supposed to be disabled?

2020-10-15 22:16 UTC, jruddell requested changes
I'd like us all to utilize css grid more. when you create elements that are opinionated on their margins you end up needing to override that in later use cases. css grid lets you space things out by defining a `gap`. This gives much more flexibility in layouts and also removes the spacing concerns from reusable components.

2020-10-15 22:27 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AzureCloudProviderFields.tsx
> +          <Button disabled type="submit">
yes for now for azure update until the API is improved

2020-10-16 01:48 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +      showToast(err, MessageTypes.error)
<img width="1621" alt="Screen Shot 2020-10-15 at 6 43 10 PM" src="https://user-images.githubusercontent.com/6668478/96203527-f93aa780-0f16-11eb-9ff3-856bc62666ac.png">

2020-10-16 17:18 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +        // TODO: surface the real API response error -- how to do this properly?
dont need this todo anymore since you are tracking and surfacing the error in the form now

2020-10-16 17:33 UTC, jruddell commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AwsCloudProviderFields.tsx
> +      <ErrorMessage>{errorMessage}</ErrorMessage>
dont render an empty element if theres no error message.

2020-10-16 17:40 UTC, jruddell approved these changes
Great work!

2020-10-16 18:56 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
> +        // TODO: surface the real API response error -- how to do this properly?
regarding this I think it would still be more ideal for the UI to surface the API request error (user can know exactly what went wrong) but I'll phrase the todo better

2020-10-16 19:29 UTC, merged