UX-600/Created Terraform Tab and API Helper
platform9/pf9-ui-plugin pull request #885
Opened 2020-10-15 01:31 UTC by knnguy

2020-10-15 05:01 UTC, jruddell requested changes
Great work! This is going to be really useful! I left some optimization / change comments down to address 😄

2020-10-15 17:52 UTC, knnguy commented on src/app/plugins/developer/components/ApiHelper.js
> +      return this.setState({ baseUrl: await apiClient.qbert.getApiEndpoint() })
I don't see the endpoint being stored in Qbert

![Screen Shot 2020-10-15 at 10 49 34 AM](https://user-images.githubusercontent.com/23369276/96167492-56613980-0ed4-11eb-8d3d-fdad17aa0e22.png)

2020-10-15 18:14 UTC, knnguy commented on src/app/plugins/kubernetes/components/apiAccess/ApiRequestHelper.tsx
> +    ;(async () => {
I actually copied that syntax from the useEffect hook in  `SummaryStep.tsx`. I'll go ahead and change in that file as well.

2020-10-15 18:24 UTC, knnguy commented on src/app/plugins/developer/components/ApiHelper.js
> +          body: JSON.parse(body),
User enters the request body in a TextField so the value is a string. That's why we need to turn it into an object

2020-10-15 22:19 UTC, jruddell commented on src/app/plugins/kubernetes/components/apiAccess/TerraformListPage.js
> +import React from 'react'
All new files should be typescript (i'm addressing this currently)

2020-10-16 00:51 UTC, knnguy commented on src/app/plugins/kubernetes/components/apiAccess/TerraformListPage.js
> +const iconSizes = { small: '', medium: '@2x', large: '@3x' }
I did change it use CloudProviderCard, but every time I hover over it, it has a border. Doesn't seem like that can be disabled in CloudProviderCard. Should I go ahead and modify CloudProviderCard?

![Screen Shot 2020-10-15 at 5 49 38 PM](https://user-images.githubusercontent.com/23369276/96200467-d3110980-0f0e-11eb-9f0b-96b431c35e18.png)

2020-10-16 01:02 UTC, knnguy commented on src/app/plugins/kubernetes/components/apiAccess/ApiRequestHelper.tsx
> +  if (paramName === 'clusterUuid') {
Not sure how you want me to do this. Map `paramName` to a component?

2020-10-16 01:10 UTC, knnguy commented on src/app/plugins/kubernetes/components/apiAccess/ApiRequestHelper.tsx
> +        ? showToast(e.message, MessageTypes.error)
Also not sure what you mean by this? Is there a component here I'm supposed to use to show the error message?

2020-10-19 06:44 UTC, closed without merging