UX-676 & UX-745/Added groups as option for rbac role bindings and fixed rbac bugs from refactor
platform9/pf9-ui-plugin pull request #931
Opened 2020-12-08 03:46 UTC by kevinylee1991

<img width="1614" alt="Screen Shot 2020-12-07 at 7 44 05 PM" src="https://user-images.githubusercontent.com/6668478/101437344-d8625300-38c4-11eb-8019-1376ec4a1d78.png">
<img width="1615" alt="Screen Shot 2020-12-07 at 7 44 37 PM" src="https://user-images.githubusercontent.com/6668478/101437351-dbf5da00-38c4-11eb-93f6-480ac767fc83.png">
<img width="1613" alt="Screen Shot 2020-12-07 at 7 44 51 PM" src="https://user-images.githubusercontent.com/6668478/101437354-dc8e7080-38c4-11eb-8d00-a1dbec90487c.png">

2020-12-08 05:29 UTC, jruddell commented on src/app/plugins/account/components/userManagement/groups/actions.js
> +      mngmGroupMappingActions,
is this an action? if so rename it to be singular.

2020-12-08 20:39 UTC, xantorres requested changes

2020-12-08 20:39 UTC, xantorres commented on src/app/plugins/account/components/userManagement/groups/actions.js
> +      mngmGroupMappingActions,
We should rename this to `mngmGroupMappingLoader` and call it with `()`, otherwise this won't do anything

2020-12-08 20:39 UTC, xantorres commented on src/app/core/components/validatedForm/withFormContext.js
> +  // const currentValue = isNil(value) ? values[id] : value
What this does is to try to pick the value from the ValidatedForm values if the value is not provided by the controlled component.
If you want to override the value provided by the ValidatedForm just initialise the input value to an empty string or 0. 
But it all depends on how you want to be handling the Picklist value, either from the picklist itself or by the `ValidatedForm`.

In any way please don't change this as it is being used in all the forms so it might cause unexpected issues.

2020-12-08 20:39 UTC, xantorres commented on src/app/plugins/kubernetes/components/common/ClusterPicklist.js
> +      if (!isEmpty(options) && selectFirst && !value) {
I don't think this is necessary

2020-12-08 23:38 UTC, kevinylee1991 commented on src/app/core/components/validatedForm/withFormContext.js
> +  // const currentValue = isNil(value) ? values[id] : value
thanks I'll give this a try

2020-12-08 23:58 UTC, kevinylee1991 commented on src/app/core/components/validatedForm/withFormContext.js
> +  // const currentValue = isNil(value) ? values[id] : value
Cool I didn't know about adding the property in the useParams initialization. That did the trick for the desync issue I was having.

2020-12-09 01:34 UTC, kevinylee1991 commented on src/app/plugins/kubernetes/components/common/ClusterPicklist.js
> +      if (!isEmpty(options) && selectFirst && !value) {
For the rbac wizards, when selecting another cluster, the clusters cache gets updated and ends up causing the clusters list to repopulate. Causes this useEffect to run again. Is there any negative effect to including the !value?

2020-12-09 01:49 UTC, xantorres commented on src/app/plugins/kubernetes/components/common/ClusterPicklist.js
> +      if (!isEmpty(options) && selectFirst && !value) {
I understand, in that case I guess it makes sense, lets keep it 
Maybe we should check other similar `Picklists` as they are following the same approach and we could potentially run into the same issue in the future.

2020-12-09 20:36 UTC, jruddell approved these changes

2020-12-09 22:48 UTC, merged